spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ansel
    username: root
    password: 123456

server:
  port: 7080

mybatis:
  mapper-locations: classpath:./mapper/*.xml

